# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag karaf-navarrop-custom-assembly
    - name: Export the Docker image
      run: docker save --output karaf-navarrop-custom-docker.tar karaf-navarrop-custom-assembly
    - name: Archive assembly production
      uses: actions/upload-artifact@v3
      with:
        name: karaf-navarrop-custom-assembly
        path: assembly/target/*.tar.gz
        retention-days: 1
    - name: Archive container production
      uses: actions/upload-artifact@v3
      with:
        name: karaf-navarrop-custom-docker
        path: a./*.tar
        retention-days: 1